//
// Created by matias on 3/21/26.
//

#ifndef PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_AVLTREE_H
#define PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_AVLTREE_H


class AVLtree {
};


#endif //PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_AVLTREE_H