//
// Created by matias on 3/21/26.
//

#ifndef PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_QUICKSORT_H
#define PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_QUICKSORT_H


class quicksort {
};


#endif //PRACTICA_1_ESTRUCTURAS_DE_DATOS_Y_ALGORITMOS_QUICKSORT_H